### ISSUE TITLE
where is the file "roscpp/SharedMemoryHeader.h"

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo-platform#13]
in this file apollo-platform/ros/ros_comm/roscpp/include/ros/publisher.h  it includes "roscpp/SharedMemoryHeader.h" , but I can`t find SharedMemoryHeader.h in the source code? where is this file?

**Comment by fengqikai1414** [comment]
@westeast "roscpp/SharedMemoryHeader.h" is a rosmsg header file, which is generated by  [ros/ros_comm/roscpp/msg/SharedMemoryHeader.msg](https://github.com/ApolloAuto/apollo-platform/blob/9b43e6cd0c873af88e2df26b019f0004afd199e9/ros/ros_comm/roscpp/msg/SharedMemoryHeader.msg)

**Comment by westeast** [comment]
@fengqikai1414 ok ,thanks very much
