### ISSUE TITLE
block and segment size question?

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo-platform#16]
In my opinion, one segment contains many blocks, by why the size of segment is 1.5 times  the size of block? 

const uint64_t ROS_SHM_BLOCK_SIZE = 2000000; // Block size, Bit
const uint64_t ROS_SHM_SEGMENT_SIZE = 3000000; // Segment size, Bit
in file shardmem_block.h

**Comment by bjtulynn** [comment]
ROS_SHM_BLOCK_SIZE is the default value for one single block, which will be resized when the message size is larger than the default value. ROS_SHM_SEGMENT_SIZE is the extra size applied to store common information, such as common data struct, wrote_num flag. It is not the total size for segment.

**Comment by quning78** [comment]
Closed for inactive questions.

Please reopen it if you have any further questions. Thanks!
