### ISSUE TITLE
Whether ros service is supported ?

### ISSUE THREAD

**Issue by MonkeyTang** [ApolloAuto/apollo-platform#17]

**Comment by westeast** [comment]
This platform just add some features to ros so it supports all ros service.

**Comment by quning78** [comment]
Other than the features we added, support all the other ROS functions as
the official release

Best wishes,
-- 
Ning Qu

**Comment by MonkeyTang** [comment]
http://wiki.ros.org/roscpp/Overview/Services, we know, the service is defined by ros msg, I want to know how can use protobuf?

**Comment by quning78** [comment]
We don't have the pb support for the service part, since we don't rely on that feature. I know they are both based on msg, however, service with pb support is not integrated yet.

**Comment by quning78** [comment]
Closed for inactive questions.

Please reopen it if you have any further questions. Thanks!
