### ISSUE TITLE
Can I use normal ubuntu kernel to use your platform?

### ISSUE THREAD

**Issue by MonkeyTang** [ApolloAuto/apollo-platform#26]
Is your apollo-kernel necessary for this ros?
Can I use normal ubuntu kernel to use your platform?
What is the difference when use apollo-kernel and normal ubuntu kernel?
It influences the performance?
I know apollo-kernel is a real time linux.

**Comment by quning78** [comment]
Sure. You can use your own kernel.

The is no dependency between apollo ros and apollo kernel yet.

For the different, you can checkout the README in apollo-kernel for more details.

**Comment by asimay** [comment]
in  README in apollo-kernel , I saw: The Apollo Kernel provides the necessary kernel level support to run Apollo software stack . so this is actually not related, right?

**Comment by quning78** [comment]
For now, you can use any kernel version with Apollo. However this could change in the future.
