### ISSUE TITLE
仿造apollo将protocbuffer移植到ros jade上遇到了问题

### ISSUE THREAD

**Issue by a3836911** [ApolloAuto/apollo-platform#45]
我按照apollo的思路将protocbuffer移植到ros jade上，并且运行pb_msg_example，talker和listener已经可以通信了，但是我确信这个通信仍然是在本地回环进行的，我尝试将etc/transport_mode.yaml复制到jade中，并没有起到任何效果，etc/transport_mode.yaml的内容正常：
transport_mode:0
topic_white_list: ["/shm_sample1", "/shm_sample2"]
我认为是这个文件没有被读取或采用，有哪位朋友做过类似的行为吗，希望能够给我一些提示

**Comment by fengqikai1414** [comment]
etc/transport_mode.yaml是共享内存通信机制的配置文件，请问有把共享内存这个功能迁移到jade吗？如果没有，肯定是不会有任何效果的。
