### ISSUE TITLE
errors occur when build apollo-platform

### ISSUE THREAD

**Issue by wang87325** [ApolloAuto/apollo-platform#59]
/usr/bin/cmake -E cmake_progress_report /home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec4110979644.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec4110979644.dir/CheckSymbolExists.c.o   -c /home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_captur
e/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec4110979644
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec4110979644.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec4110979644.dir/CheckSymbolExists.c.o  -o cmTryCompileExec4110979644 -rdynamic 
CMakeFiles/cmTryCompileExec4110979644.dir/CheckSymbolExists.c.o：在函数‘main’中：
CheckSymbolExists.c:(.text+0x16)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
make[1]:正在离开目录 `/home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec4110979644] 错误 1
make: *** [cmTryCompileExec4110979644/fast] 错误 2

File /home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec1707986552/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1707986552.dir/build.make CMakeFiles/cmTryCompileExec1707986552.dir/build
make[1]: 正在进入目录 `/home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/nvxx/software/apollo/apollo-platform-master/ros/build_isolated/audio_capture/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1707986552.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec1707986552.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-2.8/Modules/CheckFunction
Exists.c
Linking C executable cmTryCompileExec1707986552
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1707986552.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec1707986552.dir/CheckFunctionExists.c.o  -o cmTryCompileExec1707986552 -rdynamic -lpthrea
ds 
/usr/bin/ld: 找不到 -lpthreads
collect2: error: ld returned 1 exit status

**Comment by wang87325** [comment]
I have installed Apollo kernel, then install Apollo-platform and the error occured.

**Comment by fengqikai1414** [comment]
Please build apollo-platform in apollo dev docker
