### ISSUE TITLE
how to add other ros package and resolve the dependency?

### ISSUE THREAD

**Issue by niise** [ApolloAuto/apollo-platform#7]
hi 

I want to add other ros package from git repository.
do you support rosinstall_generator or other suggestion how-to?

**Comment by GoLancer** [comment]
we do not include rosinstall_generator in release yet.
you can install it in docker by the following commands:
```bash
$ sudo pip install -U rosdep rosinstall_generator wstool rosinstall
```

**Comment by niise** [comment]
after install related pack in the dev docker. 

# rosinstall_generator desktop --rosdistro indigo --deps --wet-only --tar > indigo-desktop-wet.rosinstall
i got the following error.
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/rosinstall_generator", line 11, in <module>
    from rosinstall_generator.generator import ARG_ALL_PACKAGES, ARG_CURRENT_ENVIRONMENT, generate_rosinstall, sort_rosinstall
  File "/usr/lib/python2.7/dist-packages/rosinstall_generator/generator.py", line 46, in <module>
    from rosinstall_generator.distro import get_distro as _get_wet_distro
  File "/usr/lib/python2.7/dist-packages/rosinstall_generator/distro.py", line 40, in <module>
    from rosdistro.dependency_walker import DependencyWalker, SourceDependencyWalker
ImportError: cannot import name SourceDependencyWalker
---------------------------------------------------------------------------

could you give it a try?
