### ISSUE TITLE
how to modify the code

### ISSUE THREAD

**Issue by juda** [ApolloAuto/apollo-platform#8]
Hi developers,
    Thanks for your work.
    I was wondering if I want to modified the codes from roscpp_tutorials like listener.cpp and talker.cpp, how could I recompile the code and rerun it?
    For example, I try to write an image transportation function. After I complete my code, what command should I type?

**Comment by GoLancer** [comment]
you can build your project in dev docker. for example:
```bash
$ catkin_make_isolated --install --source ros --only-pkg-with-deps roscpp_tutorials
```

**Comment by juda** [comment]
It seems that if I want to run catkin_make_isolated command, I must enter the ros environment.
 That is, run the setup.bash shell.
However, I don't know how to create a ros environment when I attempt to change source code. Released version does have setup.bash, but in such case I have no way to  modify the source code.

**Comment by juda** [comment]
Thank you for your reply. 
Could you please give me more details?
It seems that the tutorial at index page is only suitable for released version.
After I modify the source code as I describe above, how can I build a release version(application)?

**Comment by GoLancer** [comment]
Close issue after no inactive for 7 days.
