### ISSUE TITLE
想把apollo-platform移植到ros kinetic上，不知道需要改动哪些文件

### ISSUE THREAD

**Issue by DaxiongAI** [ApolloAuto/apollo-platform#84]
大家好，我想把apollo-platform移植到kinetic上，不在docker环境下，需要改动哪些文件呢？我尝试着移植，源码编译kinetic，当我启动pb_msgs_example/pb_talker时，还是提示我rosmaster未启动，当我启动roscore后，pb_talker可以正常运行。

**Comment by EgalYue** [comment]
@DaxiongAI Hi,你好,请问你这边移植成功了吗?
我现在初步打算想把apollo-platform 移植到Melodic版本, 也是不在docker环境下.
如果你这边移植成功了, 能否给我一些建议? 需要改动哪些文件呢?
