### ISSUE TITLE
apollo-platform是基于indigo的哪个commit 后修改的，怎么知道apollo-platform相对于原始的ros修改了哪些代码 ？

### ISSUE THREAD

**Issue by westeast** [ApolloAuto/apollo-platform#9]
apollo-platform是基于indigo的哪个commit 后修改的，怎么知道apollo-platform相对于原始的ros修改了哪些代码 ？

**Comment by bjtulynn** [comment]
Apollo-platform is originated from ROS Indigo release version(Indigo Igloo, May 2014), compared to original ROS, we made the following improvements to enhance its stability and performance:
* ROS Decentralization Feature
* High Efficient Communication based on Shared Memory Transport Feature
* Native Support with Protobuf Feature

You can download the source code of indigo igloo release version from ROS website(http://wiki.ros.org/indigo/Installation/Source), then by comparing the files, you can find the detailed changes we made.

**Comment by westeast** [comment]
Thank you very much ,your answer is very useful~~

**Comment by westeast** [comment]
I have compare the source code ,

And I found all the change files about shared memory in dir "/ros/ros_comm/roscpp/src/" ,But I am not sure if it is right.

so 
@bjtulynn  Can you tell me which files you have changed for the  Feature "High Efficient Communication based on Shared Memory Transport Feature"  except the dir  "/ros/ros_comm/roscpp/src/"



I want to read the source code about the Feature , Maybe I can write an article to introduce the feature in source code level。

**Comment by westeast** [comment]
##new add files
```
 src/libros/sharedmem_transport/sharedmem_block.cpp
  src/libros/sharedmem_transport/sharedmem_publisher_impl.cpp
  src/libros/sharedmem_transport/sharedmem_segment.cpp
  src/libros/sharedmem_transport/sharedmem_util.cpp
```

**Comment by bjtulynn** [comment]
Good job! For the feature "High Efficient Communication based on Shared Memory Transport Feature", the changed files are exactly these.

**Comment by bjtulynn** [comment]
Close issue after no inactive for 7 days.
